#!/usr/bin/env python3
"""Build df_save_re/structures/save_layouts.py from RE JSON artifacts."""
from __future__ import annotations

import json
from pathlib import Path
from textwrap import indent

ROOT = Path(__file__).resolve().parent.parent
DECOMP = ROOT / "ghidra_decompiles"
OUT = ROOT / "df_save_re" / "structures" / "save_layouts.py"


def _load(name: str):
    p = DECOMP / name
    if not p.is_file():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def _py_dict(d: dict) -> str:
    return repr(d)


def main() -> None:
    event_reg = _load("event_registry.json")
    event_vt = _load("event_vtables.json")
    histfig = _load("histfig_header_layout.json")
    world_secs = _load("world_reader_sections.json")

    print("build_layout_spec summary:")
    print(f"  event_registry.json: {len(event_reg) if event_reg else 'missing'}")
    print(f"  event_vtables.json: {len(event_vt) if event_vt else 'missing'}")
    print(f"  histfig_header_layout.json: {'yes' if histfig else 'missing'}")
    print(f"  world_reader_sections.json: {'yes' if world_secs else 'missing'}")

    layouts: dict[str, dict] = {}
    if histfig:
        layouts["historical_figure"] = histfig
    if event_reg:
        layouts["history_event_registry"] = {
            "source": "event_registry.json",
            "count": len(event_reg),
            "tags": {e["tag"]: e["symbol"] for e in event_reg},
        }

    lines = [
        '"""Decompile-derived on-disk save layouts (generated/curated from Ghidra RE)."""',
        "",
        "# Generated by scripts/build_layout_spec.py — do not hand-edit; re-run script.",
        f"SAVE_LAYOUTS: dict[str, dict] = {_py_dict(layouts)}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {OUT} ({len(layouts)} struct entries)")


if __name__ == "__main__":
    main()
